# port
server.port=4000
server.servlet.context-path=/api
protocol.subdomain = http://localhost:4000
#http://localhost:4000/api/swagger-ui/index.html

#database prod 
spring.datasource.url=jdbc:mysql://localhost:3306/wholesale?useSSL=false&serverTimezone=Asia/Kuala_Lumpur
spring.datasource.username=wholesale_admin
spring.datasource.password=Wholesale_2026_Secure_Success

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=false

#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# App Properties
app.jwtCookieName=jwtCookieInternationalPayment
app.jwtSecret=InternationalPaymentLocalDevelopmentJwtSecretKeyThatIsDefinitelyLongerThanSixtyFourCharactersForHS512Signing

app.jwtExpirationMs=864000000
build.version=@project.version@

# image asset
image.assets.location=C:/Users/nurai/OneDrive/Documents/LocalImages/eastel-int-pay
#image.assets.location=/home/ubuntu/modules/international-payment/assets

#WSP Reqeust
wsp.username=enrich
wsp.password=enrich
wsp.getTokenUrl=https://iatsuat.mtradeasia.com:2083/auth
wsp.billpaymenturl=https://iatsuat.mtradeasia.com:2083/transaction/billPayment
wsp.topupurl=https://iatsuat.mtradeasia.com:2083/transaction/submit
wsp.getvoucherurl=https://iatsuat.mtradeasia.com:2083/transaction/voucher
wsp.getretailrate=https://iatsuat.mtradeasia.com:2083/get/customerRetailRate/
wsp.getoperatorurl=https://iatsuat.mtradeasia.com:2083/queryOperator?
wsp.getQueryTransactionUrl=https://iatsuat.mtradeasia.com:2083/transaction/status
wsp.getValidateBillUrl=https://iatsuat.mtradeasia.com:2083/transaction/validateBill

# celcom.api.url=https://igw.api.celcom.com.my/mvnoregistration/v1

#MMPAYMENT
mmGetTokenUrl=https://www.merchantrademoney.com/api/mmpay/token
mmPaymentUrl=https://www.merchantrademoney.com/api/mmpay/pay
mmValidateUrl=https://www.merchantrademoney.com/api/mmpay/otpresponse
mmResendOtpUrl=https://www.merchantrademoney.com/api/mmpay/otpresend
mmPaymentStatusUrl=https://www.merchantrademoney.com/api/mmpay/paystatus
mmRefundPaymentUrl=https://www.merchantrademoney.com/api/mmpay/refund
pass=85D2B533-7828-47A7-BB9F-E55C3FAB9F02
key=38B8DD45-8766-4641-8D53-493292D62118
host=www.merchantrademoney.com

# BWALLET PREPROD
BWALLET_PAYMENT_URL=https://uatbocorpclient.mtradeasia.com

BWALLET_PAYMENT_PUBLIC_KEY=7EED33A0-51D3-4932-AE4E-090E4C2C9960
BWALLET_PAYMENT_PRIVATE_KEY=8422ad9d-e3a1-493a-872c-44a26eff823e

BWALLET_PAYMENT_PUBLIC_KEY_DOMES=7EED33A0-51D3-4932-AE4E-090E4C2C9960
BWALLET_PAYMENT_PRIVATE_KEY_DOMES=8422ad9d-e3a1-493a-872c-44a26eff823e

BWALLET_PAYMENT_PUBLIC_KEY_UTILITY=7EED33A0-51D3-4932-AE4E-090E4C2C9960
BWALLET_PAYMENT_PRIVATE_KEY_UTILITY=8422ad9d-e3a1-493a-872c-44a26eff823e

BWALLET_PAYMENT_PUBLIC_KEY_VOUCHER=7EED33A0-51D3-4932-AE4E-090E4C2C9960
BWALLET_PAYMENT_PRIVATE_KEY_VOUCHER=8422ad9d-e3a1-493a-872c-44a26eff823e

BWALLET_PAYMENT_PUBLIC_KEY_ENTERTAINMENT=7EED33A0-51D3-4932-AE4E-090E4C2C9960
BWALLET_PAYMENT_PRIVATE_KEY_ENTERTAINMENT=8422ad9d-e3a1-493a-872c-44a26eff823e

#ORDER_SERVICE
orderUrl=https://uatapi.e-kedai.my/order-service/

#UMG
umgUser=ekedai
umgPassword=Ekedai@Pw1
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
umgSenderAddress=ekedai

#email kedai
# spring.mail.host=smtp.gmail.com
# spring.mail.port=465
# spring.mail.username=notification@mcoopon.my
# spring.mail.password=rhyyelakwupefhrg
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.socketFactory.port=465
# spring.mail.properties.mail.smtp.socketFactory.class=jakarta.net.ssl.SSLSocketFactory


#local email (temp personal acc)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
email.notification=false


# Output terminal style
spring.output.ansi.enabled=always

central.auth.service.secretString=SOVtZUWLxsPjR9Q/sE1EeDxxoB9S9sehL8+VLGFsrG0nvVgKVro54JxC2+2C8L5nli/3IktXnMYv8z9FHZ4vYA==
useSwagger=true
allowed.origins=http://localhost:4200,http://localhost:8100

umgUrl=https://umgotp.hellosim.com.my/api/processMsg.php


channel.name=test

#to bypass somethings is local env
isLocal=true

